 final List<Map<String, String>> countriesList = [
  {'code': 'AF', 'name': 'Afghanistan', 'flag': 'https://flagcdn.com/24x18/af.png'},
  {'code': 'AL', 'name': 'Albania', 'flag': 'https://flagcdn.com/24x18/al.png'},
  {'code': 'DZ', 'name': 'Algeria', 'flag': 'https://flagcdn.com/24x18/dz.png'},
  {'code': 'AS', 'name': 'American Samoa', 'flag': 'https://flagcdn.com/24x18/as.png'},
  {'code': 'AD', 'name': 'Andorra', 'flag': 'https://flagcdn.com/24x18/ad.png'},
  {'code': 'AO', 'name': 'Angola', 'flag': 'https://flagcdn.com/24x18/ao.png'},
  {'code': 'AI', 'name': 'Anguilla', 'flag': 'https://flagcdn.com/24x18/ai.png'},
  {'code': 'AQ', 'name': 'Antarctica', 'flag': 'https://flagcdn.com/24x18/aq.png'},
  {'code': 'AG', 'name': 'Antigua and Barbuda', 'flag': 'https://flagcdn.com/24x18/ag.png'},
  {'code': 'AR', 'name': 'Argentina', 'flag': 'https://flagcdn.com/24x18/ar.png'},
  {'code': 'AM', 'name': 'Armenia', 'flag': 'https://flagcdn.com/24x18/am.png'},
  {'code': 'AW', 'name': 'Aruba', 'flag': 'https://flagcdn.com/24x18/aw.png'},
  {'code': 'AU', 'name': 'Australia', 'flag': 'https://flagcdn.com/24x18/au.png'},
  {'code': 'AT', 'name': 'Austria', 'flag': 'https://flagcdn.com/24x18/at.png'},
  {'code': 'AZ', 'name': 'Azerbaijan', 'flag': 'https://flagcdn.com/24x18/az.png'},
  {'code': 'BS', 'name': 'Bahamas', 'flag': 'https://flagcdn.com/24x18/bs.png'},
  {'code': 'BH', 'name': 'Bahrain', 'flag': 'https://flagcdn.com/24x18/bh.png'},
  {'code': 'BD', 'name': 'Bangladesh', 'flag': 'https://flagcdn.com/24x18/bd.png'},
  {'code': 'BB', 'name': 'Barbados', 'flag': 'https://flagcdn.com/24x18/bb.png'},
  {'code': 'BY', 'name': 'Belarus', 'flag': 'https://flagcdn.com/24x18/by.png'},
  {'code': 'BE', 'name': 'Belgium', 'flag': 'https://flagcdn.com/24x18/be.png'},
  {'code': 'BZ', 'name': 'Belize', 'flag': 'https://flagcdn.com/24x18/bz.png'},
  {'code': 'BJ', 'name': 'Benin', 'flag': 'https://flagcdn.com/24x18/bj.png'},
  {'code': 'BM', 'name': 'Bermuda', 'flag': 'https://flagcdn.com/24x18/bm.png'},
  {'code': 'BT', 'name': 'Bhutan', 'flag': 'https://flagcdn.com/24x18/bt.png'},
  {'code': 'BO', 'name': 'Bolivia', 'flag': 'https://flagcdn.com/24x18/bo.png'},
  {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'flag': 'https://flagcdn.com/24x18/ba.png'},
  {'code': 'BW', 'name': 'Botswana', 'flag': 'https://flagcdn.com/24x18/bw.png'},
  {'code': 'BV', 'name': 'Bouvet Island', 'flag': 'https://flagcdn.com/24x18/bv.png'},
  {'code': 'BR', 'name': 'Brazil', 'flag': 'https://flagcdn.com/24x18/br.png'},
  {'code': 'IO', 'name': 'British Indian Ocean Territory', 'flag': 'https://flagcdn.com/24x18/io.png'},
  {'code': 'BN', 'name': 'Brunei Darussalam', 'flag': 'https://flagcdn.com/24x18/bn.png'},
  {'code': 'BG', 'name': 'Bulgaria', 'flag': 'https://flagcdn.com/24x18/bg.png'},
  {'code': 'BF', 'name': 'Burkina Faso', 'flag': 'https://flagcdn.com/24x18/bf.png'},
  {'code': 'BI', 'name': 'Burundi', 'flag': 'https://flagcdn.com/24x18/bi.png'},
  {'code': 'KH', 'name': 'Cambodia', 'flag': 'https://flagcdn.com/24x18/kh.png'},
  {'code': 'CM', 'name': 'Cameroon', 'flag': 'https://flagcdn.com/24x18/cm.png'},
  {'code': 'CA', 'name': 'Canada', 'flag': 'https://flagcdn.com/24x18/ca.png'},
  {'code': 'CV', 'name': 'Cape Verde', 'flag': 'https://flagcdn.com/24x18/cv.png'},
  {'code': 'KY', 'name': 'Cayman Islands', 'flag': 'https://flagcdn.com/24x18/ky.png'},
  {'code': 'CF', 'name': 'Central African Republic', 'flag': 'https://flagcdn.com/24x18/cf.png'},
  {'code': 'TD', 'name': 'Chad', 'flag': 'https://flagcdn.com/24x18/td.png'},
  {'code': 'CL', 'name': 'Chile', 'flag': 'https://flagcdn.com/24x18/cl.png'},
  {'code': 'CN', 'name': 'China', 'flag': 'https://flagcdn.com/24x18/cn.png'},
  {'code': 'CX', 'name': 'Christmas Island', 'flag': 'https://flagcdn.com/24x18/cx.png'},
  {'code': 'CC', 'name': 'Cocos (Keeling) Islands', 'flag': 'https://flagcdn.com/24x18/cc.png'},
  {'code': 'CO', 'name': 'Colombia', 'flag': 'https://flagcdn.com/24x18/co.png'},
  {'code': 'KM', 'name': 'Comoros', 'flag': 'https://flagcdn.com/24x18/km.png'},
  {'code': 'CG', 'name': 'Congo', 'flag': 'https://flagcdn.com/24x18/cg.png'},
  {'code': 'CD', 'name': 'Congo, the Democratic Republic of the', 'flag': 'https://flagcdn.com/24x18/cd.png'},
  {'code': 'CK', 'name': 'Cook Islands', 'flag': 'https://flagcdn.com/24x18/ck.png'},
  {'code': 'CR', 'name': 'Costa Rica', 'flag': 'https://flagcdn.com/24x18/cr.png'},
  {'code': 'CI', 'name': "Cote D'Ivoire", 'flag': 'https://flagcdn.com/24x18/ci.png'},
  {'code': 'HR', 'name': 'Croatia', 'flag': 'https://flagcdn.com/24x18/hr.png'},
  {'code': 'CU', 'name': 'Cuba', 'flag': 'https://flagcdn.com/24x18/cu.png'},
  {'code': 'CY', 'name': 'Cyprus', 'flag': 'https://flagcdn.com/24x18/cy.png'},
  {'code': 'CZ', 'name': 'Czech Republic', 'flag': 'https://flagcdn.com/24x18/cz.png'},
  {'code': 'DK', 'name': 'Denmark', 'flag': 'https://flagcdn.com/24x18/dk.png'},
  {'code': 'DJ', 'name': 'Djibouti', 'flag': 'https://flagcdn.com/24x18/dj.png'},
  {'code': 'DM', 'name': 'Dominica', 'flag': 'https://flagcdn.com/24x18/dm.png'},
  {'code': 'DO', 'name': 'Dominican Republic', 'flag': 'https://flagcdn.com/24x18/do.png'},
  {'code': 'EC', 'name': 'Ecuador', 'flag': 'https://flagcdn.com/24x18/ec.png'},
  {'code': 'EG', 'name': 'Egypt', 'flag': 'https://flagcdn.com/24x18/eg.png'},
  {'code': 'SV', 'name': 'El Salvador', 'flag': 'https://flagcdn.com/24x18/sv.png'},
  {'code': 'GQ', 'name': 'Equatorial Guinea', 'flag': 'https://flagcdn.com/24x18/gq.png'},
  {'code': 'ER', 'name': 'Eritrea', 'flag': 'https://flagcdn.com/24x18/er.png'},
  {'code': 'EE', 'name': 'Estonia', 'flag': 'https://flagcdn.com/24x18/ee.png'},
  {'code': 'ET', 'name': 'Ethiopia', 'flag': 'https://flagcdn.com/24x18/et.png'},
  {'code': 'FK', 'name': 'Falkland Islands (Malvinas)', 'flag': 'https://flagcdn.com/24x18/fk.png'},
  {'code': 'FO', 'name': 'Faroe Islands', 'flag': 'https://flagcdn.com/24x18/fo.png'},
  {'code': 'FJ', 'name': 'Fiji', 'flag': 'https://flagcdn.com/24x18/fj.png'},
  {'code': 'FI', 'name': 'Finland', 'flag': 'https://flagcdn.com/24x18/fi.png'},
  {'code': 'FR', 'name': 'France', 'flag': 'https://flagcdn.com/24x18/fr.png'},
  {'code': 'GF', 'name': 'French Guiana', 'flag': 'https://flagcdn.com/24x18/gf.png'},
  {'code': 'PF', 'name': 'French Polynesia', 'flag': 'https://flagcdn.com/24x18/pf.png'},
  {'code': 'TF', 'name': 'French Southern Territories', 'flag': 'https://flagcdn.com/24x18/tf.png'},
  {'code': 'GA', 'name': 'Gabon', 'flag': 'https://flagcdn.com/24x18/ga.png'},
  {'code': 'GM', 'name': 'Gambia', 'flag': 'https://flagcdn.com/24x18/gm.png'},
  {'code': 'GE', 'name': 'Georgia', 'flag': 'https://flagcdn.com/24x18/ge.png'},
  {'code': 'DE', 'name': 'Germany', 'flag': 'https://flagcdn.com/24x18/de.png'},
  {'code': 'GH', 'name': 'Ghana', 'flag': 'https://flagcdn.com/24x18/gh.png'},
  {'code': 'GI', 'name': 'Gibraltar', 'flag': 'https://flagcdn.com/24x18/gi.png'},
  {'code': 'GR', 'name': 'Greece', 'flag': 'https://flagcdn.com/24x18/gr.png'},
  {'code': 'GL', 'name': 'Greenland', 'flag': 'https://flagcdn.com/24x18/gl.png'},
  {'code': 'GD', 'name': 'Grenada', 'flag': 'https://flagcdn.com/24x18/gd.png'},
  {'code': 'GP', 'name': 'Guadeloupe', 'flag': 'https://flagcdn.com/24x18/gp.png'},
  {'code': 'GU', 'name': 'Guam', 'flag': 'https://flagcdn.com/24x18/gu.png'},
  {'code': 'GT', 'name': 'Guatemala', 'flag': 'https://flagcdn.com/24x18/gt.png'},
  {'code': 'GN', 'name': 'Guinea', 'flag': 'https://flagcdn.com/24x18/gn.png'},
  {'code': 'GW', 'name': 'Guinea-Bissau', 'flag': 'https://flagcdn.com/24x18/gw.png'},
  {'code': 'GY', 'name': 'Guyana', 'flag': 'https://flagcdn.com/24x18/gy.png'},
  {'code': 'HT', 'name': 'Haiti', 'flag': 'https://flagcdn.com/24x18/ht.png'},
  {'code': 'HM', 'name': 'Heard Island and Mcdonald Islands', 'flag': 'https://flagcdn.com/24x18/hm.png'},
  {'code': 'VA', 'name': 'Holy See (Vatican City State)', 'flag': 'https://flagcdn.com/24x18/va.png'},
  {'code': 'HN', 'name': 'Honduras', 'flag': 'https://flagcdn.com/24x18/hn.png'},
  {'code': 'HK', 'name': 'Hong Kong', 'flag': 'https://flagcdn.com/24x18/hk.png'},
  {'code': 'HU', 'name': 'Hungary', 'flag': 'https://flagcdn.com/24x18/hu.png'},
  {'code': 'IS', 'name': 'Iceland', 'flag': 'https://flagcdn.com/24x18/is.png'},
  {'code': 'IN', 'name': 'India', 'flag': 'https://flagcdn.com/24x18/in.png'},
  {'code': 'ID', 'name': 'Indonesia', 'flag': 'https://flagcdn.com/24x18/id.png'},
  {'code': 'IR', 'name': 'Iran, Islamic Republic of', 'flag': 'https://flagcdn.com/24x18/ir.png'},
  {'code': 'IQ', 'name': 'Iraq', 'flag': 'https://flagcdn.com/24x18/iq.png'},
  {'code': 'IE', 'name': 'Ireland', 'flag': 'https://flagcdn.com/24x18/ie.png'},
  {'code': 'IL', 'name': 'Israel', 'flag': 'https://flagcdn.com/24x18/il.png'},
  {'code': 'IT', 'name': 'Italy', 'flag': 'https://flagcdn.com/24x18/it.png'},
  {'code': 'JM', 'name': 'Jamaica', 'flag': 'https://flagcdn.com/24x18/jm.png'},
  {'code': 'JP', 'name': 'Japan', 'flag': 'https://flagcdn.com/24x18/jp.png'},
  {'code': 'JO', 'name': 'Jordan', 'flag': 'https://flagcdn.com/24x18/jo.png'},
  {'code': 'KZ', 'name': 'Kazakhstan', 'flag': 'https://flagcdn.com/24x18/kz.png'},
  {'code': 'KE', 'name': 'Kenya', 'flag': 'https://flagcdn.com/24x18/ke.png'},
  {'code': 'KI', 'name': 'Kiribati', 'flag': 'https://flagcdn.com/24x18/ki.png'},
  {'code': 'KP', 'name': "Korea, Democratic People's Republic of", 'flag': 'https://flagcdn.com/24x18/kp.png'},
  {'code': 'KR', 'name': 'Korea, Republic of', 'flag': 'https://flagcdn.com/24x18/kr.png'},
  {'code': 'KW', 'name': 'Kuwait', 'flag': 'https://flagcdn.com/24x18/kw.png'},
  {'code': 'KG', 'name': 'Kyrgyzstan', 'flag': 'https://flagcdn.com/24x18/kg.png'},
  {'code': 'LA', 'name': "Lao People's Democratic Republic", 'flag': 'https://flagcdn.com/24x18/la.png'},
  {'code': 'LV', 'name': 'Latvia', 'flag': 'https://flagcdn.com/24x18/lv.png'},
  {'code': 'LB', 'name': 'Lebanon', 'flag': 'https://flagcdn.com/24x18/lb.png'},
  {'code': 'LS', 'name': 'Lesotho', 'flag': 'https://flagcdn.com/24x18/ls.png'},
  {'code': 'LR', 'name': 'Liberia', 'flag': 'https://flagcdn.com/24x18/lr.png'},
  {'code': 'LY', 'name': 'Libyan Arab Jamahiriya', 'flag': 'https://flagcdn.com/24x18/ly.png'},
  {'code': 'LI', 'name': 'Liechtenstein', 'flag': 'https://flagcdn.com/24x18/li.png'},
  {'code': 'LT', 'name': 'Lithuania', 'flag': 'https://flagcdn.com/24x18/lt.png'},
  {'code': 'LU', 'name': 'Luxembourg', 'flag': 'https://flagcdn.com/24x18/lu.png'},
  {'code': 'MO', 'name': 'Macao', 'flag': 'https://flagcdn.com/24x18/mo.png'},
  {'code': 'MK', 'name': 'Macedonia, the Former Yugoslav Republic of', 'flag': 'https://flagcdn.com/24x18/mk.png'},
  {'code': 'MG', 'name': 'Madagascar', 'flag': 'https://flagcdn.com/24x18/mg.png'},
  {'code': 'MW', 'name': 'Malawi', 'flag': 'https://flagcdn.com/24x18/mw.png'},
  {'code': 'MY', 'name': 'Malaysia', 'flag': 'https://flagcdn.com/24x18/my.png'},
  {'code': 'MV', 'name': 'Maldives', 'flag': 'https://flagcdn.com/24x18/mv.png'},
  {'code': 'ML', 'name': 'Mali', 'flag': 'https://flagcdn.com/24x18/ml.png'},
  {'code': 'MT', 'name': 'Malta', 'flag': 'https://flagcdn.com/24x18/mt.png'},
  {'code': 'MH', 'name': 'Marshall Islands', 'flag': 'https://flagcdn.com/24x18/mh.png'},
  {'code': 'MQ', 'name': 'Martinique', 'flag': 'https://flagcdn.com/24x18/mq.png'},
  {'code': 'MR', 'name': 'Mauritania', 'flag': 'https://flagcdn.com/24x18/mr.png'},
  {'code': 'MU', 'name': 'Mauritius', 'flag': 'https://flagcdn.com/24x18/mu.png'},
  {'code': 'YT', 'name': 'Mayotte', 'flag': 'https://flagcdn.com/24x18/yt.png'},
  {'code': 'MX', 'name': 'Mexico', 'flag': 'https://flagcdn.com/24x18/mx.png'},
  {'code': 'FM', 'name': 'Micronesia, Federated States of', 'flag': 'https://flagcdn.com/24x18/fm.png'},
  {'code': 'MD', 'name': 'Moldova, Republic of', 'flag': 'https://flagcdn.com/24x18/md.png'},
  {'code': 'MC', 'name': 'Monaco', 'flag': 'https://flagcdn.com/24x18/mc.png'},
  {'code': 'MN', 'name': 'Mongolia', 'flag': 'https://flagcdn.com/24x18/mn.png'},
  {'code': 'MS', 'name': 'Montserrat', 'flag': 'https://flagcdn.com/24x18/ms.png'},
  {'code': 'MA', 'name': 'Morocco', 'flag': 'https://flagcdn.com/24x18/ma.png'},
  {'code': 'MZ', 'name': 'Mozambique', 'flag': 'https://flagcdn.com/24x18/mz.png'},
  {'code': 'MM', 'name': 'Myanmar', 'flag': 'https://flagcdn.com/24x18/mm.png'},
  {'code': 'NA', 'name': 'Namibia', 'flag': 'https://flagcdn.com/24x18/na.png'},
  {'code': 'NR', 'name': 'Nauru', 'flag': 'https://flagcdn.com/24x18/nr.png'},
  {'code': 'NP', 'name': 'Nepal', 'flag': 'https://flagcdn.com/24x18/np.png'},
  {'code': 'NL', 'name': 'Netherlands', 'flag': 'https://flagcdn.com/24x18/nl.png'},
  {'code': 'AN', 'name': 'Netherlands Antilles', 'flag': 'https://flagcdn.com/24x18/an.png'},
  {'code': 'NC', 'name': 'New Caledonia', 'flag': 'https://flagcdn.com/24x18/nc.png'},
  {'code': 'NZ', 'name': 'New Zealand', 'flag': 'https://flagcdn.com/24x18/nz.png'},
  {'code': 'NI', 'name': 'Nicaragua', 'flag': 'https://flagcdn.com/24x18/ni.png'},
  {'code': 'NE', 'name': 'Niger', 'flag': 'https://flagcdn.com/24x18/ne.png'},
  {'code': 'NG', 'name': 'Nigeria', 'flag': 'https://flagcdn.com/24x18/ng.png'},
  {'code': 'NU', 'name': 'Niue', 'flag': 'https://flagcdn.com/24x18/nu.png'},
  {'code': 'NF', 'name': 'Norfolk Island', 'flag': 'https://flagcdn.com/24x18/nf.png'},
  {'code': 'MP', 'name': 'Northern Mariana Islands', 'flag': 'https://flagcdn.com/24x18/mp.png'},
  {'code': 'NO', 'name': 'Norway', 'flag': 'https://flagcdn.com/24x18/no.png'},
  {'code': 'OM', 'name': 'Oman', 'flag': 'https://flagcdn.com/24x18/om.png'},
  {'code': 'PK', 'name': 'Pakistan', 'flag': 'https://flagcdn.com/24x18/pk.png'},
  {'code': 'PW', 'name': 'Palau', 'flag': 'https://flagcdn.com/24x18/pw.png'},
  {'code': 'PS', 'name': 'Palestinian Territory, Occupied', 'flag': 'https://flagcdn.com/24x18/ps.png'},
  {'code': 'PA', 'name': 'Panama', 'flag': 'https://flagcdn.com/24x18/pa.png'},
  {'code': 'PG', 'name': 'Papua New Guinea', 'flag': 'https://flagcdn.com/24x18/pg.png'},
  {'code': 'PY', 'name': 'Paraguay', 'flag': 'https://flagcdn.com/24x18/py.png'},
  {'code': 'PE', 'name': 'Peru', 'flag': 'https://flagcdn.com/24x18/pe.png'},
  {'code': 'PH', 'name': 'Philippines', 'flag': 'https://flagcdn.com/24x18/ph.png'},
  {'code': 'PN', 'name': 'Pitcairn', 'flag': 'https://flagcdn.com/24x18/pn.png'},
  {'code': 'PL', 'name': 'Poland', 'flag': 'https://flagcdn.com/24x18/pl.png'},
  {'code': 'PT', 'name': 'Portugal', 'flag': 'https://flagcdn.com/24x18/pt.png'},
  {'code': 'PR', 'name': 'Puerto Rico', 'flag': 'https://flagcdn.com/24x18/pr.png'},
  {'code': 'QA', 'name': 'Qatar', 'flag': 'https://flagcdn.com/24x18/qa.png'},
  {'code': 'RE', 'name': 'Reunion', 'flag': 'https://flagcdn.com/24x18/re.png'},
  {'code': 'RO', 'name': 'Romania', 'flag': 'https://flagcdn.com/24x18/ro.png'},
  {'code': 'RU', 'name': 'Russian Federation', 'flag': 'https://flagcdn.com/24x18/ru.png'},
  {'code': 'RW', 'name': 'Rwanda', 'flag': 'https://flagcdn.com/24x18/rw.png'},
  {'code': 'SH', 'name': 'Saint Helena', 'flag': 'https://flagcdn.com/24x18/sh.png'},
  {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'flag': 'https://flagcdn.com/24x18/kn.png'},
  {'code': 'LC', 'name': 'Saint Lucia', 'flag': 'https://flagcdn.com/24x18/lc.png'},
  {'code': 'PM', 'name': 'Saint Pierre and Miquelon', 'flag': 'https://flagcdn.com/24x18/pm.png'},
  {'code': 'VC', 'name': 'Saint Vincent and the Grenadines', 'flag': 'https://flagcdn.com/24x18/vc.png'},
  {'code': 'WS', 'name': 'Samoa', 'flag': 'https://flagcdn.com/24x18/ws.png'},
  {'code': 'SM', 'name': 'San Marino', 'flag': 'https://flagcdn.com/24x18/sm.png'},
  {'code': 'ST', 'name': 'Sao Tome and Principe', 'flag': 'https://flagcdn.com/24x18/st.png'},
  {'code': 'SA', 'name': 'Saudi Arabia', 'flag': 'https://flagcdn.com/24x18/sa.png'},
  {'code': 'SN', 'name': 'Senegal', 'flag': 'https://flagcdn.com/24x18/sn.png'},
  {'code': 'CS', 'name': 'Serbia and Montenegro', 'flag': 'https://flagcdn.com/24x18/cs.png'},
  {'code': 'SC', 'name': 'Seychelles', 'flag': 'https://flagcdn.com/24x18/sc.png'},
  {'code': 'SL', 'name': 'Sierra Leone', 'flag': 'https://flagcdn.com/24x18/sl.png'},
  {'code': 'SG', 'name': 'Singapore', 'flag': 'https://flagcdn.com/24x18/sg.png'},
  {'code': 'SK', 'name': 'Slovakia', 'flag': 'https://flagcdn.com/24x18/sk.png'},
  {'code': 'SI', 'name': 'Slovenia', 'flag': 'https://flagcdn.com/24x18/si.png'},
  {'code': 'SB', 'name': 'Solomon Islands', 'flag': 'https://flagcdn.com/24x18/sb.png'},
  {'code': 'SO', 'name': 'Somalia', 'flag': 'https://flagcdn.com/24x18/so.png'},
  {'code': 'ZA', 'name': 'South Africa', 'flag': 'https://flagcdn.com/24x18/za.png'},
  {'code': 'GS', 'name': 'South Georgia and the South Sandwich Islands', 'flag': 'https://flagcdn.com/24x18/gs.png'},
  {'code': 'ES', 'name': 'Spain', 'flag': 'https://flagcdn.com/24x18/es.png'},
  {'code': 'LK', 'name': 'Sri Lanka', 'flag': 'https://flagcdn.com/24x18/lk.png'},
  {'code': 'SD', 'name': 'Sudan', 'flag': 'https://flagcdn.com/24x18/sd.png'},
  {'code': 'SR', 'name': 'Suriname', 'flag': 'https://flagcdn.com/24x18/sr.png'},
  {'code': 'SJ', 'name': 'Svalbard and Jan Mayen', 'flag': 'https://flagcdn.com/24x18/sj.png'},
  {'code': 'SZ', 'name': 'Swaziland', 'flag': 'https://flagcdn.com/24x18/sz.png'},
  {'code': 'SE', 'name': 'Sweden', 'flag': 'https://flagcdn.com/24x18/se.png'},
  {'code': 'CH', 'name': 'Switzerland', 'flag': 'https://flagcdn.com/24x18/ch.png'},
  {'code': 'SY', 'name': 'Syrian Arab Republic', 'flag': 'https://flagcdn.com/24x18/sy.png'},
  {'code': 'TW', 'name': 'Taiwan, Province of China', 'flag': 'https://flagcdn.com/24x18/tw.png'},
  {'code': 'TJ', 'name': 'Tajikistan', 'flag': 'https://flagcdn.com/24x18/tj.png'},
  {'code': 'TZ', 'name': 'Tanzania, United Republic of', 'flag': 'https://flagcdn.com/24x18/tz.png'},
  {'code': 'TH', 'name': 'Thailand', 'flag': 'https://flagcdn.com/24x18/th.png'},
  {'code': 'TL', 'name': 'Timor-Leste', 'flag': 'https://flagcdn.com/24x18/tl.png'},
  {'code': 'TG', 'name': 'Togo', 'flag': 'https://flagcdn.com/24x18/tg.png'},
  {'code': 'TK', 'name': 'Tokelau', 'flag': 'https://flagcdn.com/24x18/tk.png'},
  {'code': 'TO', 'name': 'Tonga', 'flag': 'https://flagcdn.com/24x18/to.png'},
  {'code': 'TT', 'name': 'Trinidad and Tobago', 'flag': 'https://flagcdn.com/24x18/tt.png'},
  {'code': 'TN', 'name': 'Tunisia', 'flag': 'https://flagcdn.com/24x18/tn.png'},
  {'code': 'TR', 'name': 'Turkey', 'flag': 'https://flagcdn.com/24x18/tr.png'},
  {'code': 'TM', 'name': 'Turkmenistan', 'flag': 'https://flagcdn.com/24x18/tm.png'},
  {'code': 'TC', 'name': 'Turks and Caicos Islands', 'flag': 'https://flagcdn.com/24x18/tc.png'},
  {'code': 'TV', 'name': 'Tuvalu', 'flag': 'https://flagcdn.com/24x18/tv.png'},
  {'code': 'UG', 'name': 'Uganda', 'flag': 'https://flagcdn.com/24x18/ug.png'},
  {'code': 'UA', 'name': 'Ukraine', 'flag': 'https://flagcdn.com/24x18/ua.png'},
  {'code': 'AE', 'name': 'United Arab Emirates', 'flag': 'https://flagcdn.com/24x18/ae.png'},
  {'code': 'GB', 'name': 'United Kingdom', 'flag': 'https://flagcdn.com/24x18/gb.png'},
  {'code': 'US', 'name': 'United States', 'flag': 'https://flagcdn.com/24x18/us.png'},
  {'code': 'UM', 'name': 'United States Minor Outlying Islands', 'flag': 'https://flagcdn.com/24x18/um.png'},
  {'code': 'UY', 'name': 'Uruguay', 'flag': 'https://flagcdn.com/24x18/uy.png'},
  {'code': 'UZ', 'name': 'Uzbekistan', 'flag': 'https://flagcdn.com/24x18/uz.png'},
  {'code': 'VU', 'name': 'Vanuatu', 'flag': 'https://flagcdn.com/24x18/vu.png'},
  {'code': 'VE', 'name': 'Venezuela', 'flag': 'https://flagcdn.com/24x18/ve.png'},
  {'code': 'VN', 'name': 'Viet Nam', 'flag': 'https://flagcdn.com/24x18/vn.png'},
  {'code': 'VG', 'name': 'Virgin Islands, British', 'flag': 'https://flagcdn.com/24x18/vg.png'},
  {'code': 'VI', 'name': 'Virgin Islands, U.s.', 'flag': 'https://flagcdn.com/24x18/vi.png'},
  {'code': 'WF', 'name': 'Wallis and Futuna', 'flag': 'https://flagcdn.com/24x18/wf.png'},
  {'code': 'EH', 'name': 'Western Sahara', 'flag': 'https://flagcdn.com/24x18/eh.png'},
  {'code': 'YE', 'name': 'Yemen', 'flag': 'https://flagcdn.com/24x18/ye.png'},
  {'code': 'ZM', 'name': 'Zambia', 'flag': 'https://flagcdn.com/24x18/zm.png'},
  {'code': 'ZW', 'name': 'Zimbabwe', 'flag': 'https://flagcdn.com/24x18/zw.png'},
]; 